project:
  type: book
  output-dir: docs

book:
  title: "The Sira Project"
  chapters:
    - index.qmd
    - editorial-method.qmd
    - witnesses/WABAW.qmd

lang: en

format:
  html:
    toc: true
    toc-depth: 2
    number-sections: false
    reference-location: margin
    css: assets/sira.css